Title:	Arc42 Template 
Author:	Markus Schärtel
Affiliation:	Bosch Software Innovations
Date:	13.11.2012 
Comment:	Initial Version
Quotes Language:	english

# Architecture Documentation „Here goes your system name"[^arc42_template_mentioning]

		created by Markus Schärtel

---

[^arc42_template_mentioning]: Template Revision:	6.1 EN June 2012

	We acknowledge that this document uses material from the arc 42 architecture template, [http://www.arc42.de](http://www.arc42.de). 
	Created by Dr. Peter Hruschka & Dr. Gernot Starke.
	The Markdown template was created and provided by Markus Schärtel


| Version 	| Date 	| Reviser 	| Description	|
| -----	| -----	| ----	| ----	|
| 0.9 	| 13.11.2012 	| Markus Schärtel 	| Initial Version 	|
| 0.9.1 	| 02.02.2013 	| Markus Schärtel 	| Corrected linebreaks and added SNIPs 	|
[Revision History]


| Document 	| Description 	|
| -----	| -----	|
| 	| 	|
[Related Documents]

-----

> Written and generated with <a href=„http:/bywordapp.com/“><strong>Byword</strong></a>

-----

# Table of Content [TOC]

1. [Introduction and Goals][section-introduction-and-goals]
2. [Architecture Constraints][section-architecture-constraints]
3. [System Scope and Context][section-system-scope-and-context]
4. [Solution Strategy][section-solution-strategy]
5. [Building Block View][section-building-block-view]
6. [Runtime View][section-runtime-view]
7. [Deployment View][section-deployment-view]
8. [Concepts][section-concepts]
9. [Design Decisions][section-design-decisions]
10. [Quality Scenarios][section-quality-scenarios]
11. [Technical Risks][section-technical-risks]
12.  [Glossary][section-glossary]

—

# 1. Introduction and Goals [section-introduction-and-goals]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/01_introduction_and_goals.mmd]

# 2. Architecture Constraints[section-architecture-constraints]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/02_architecture_constraints.mmd]

# 3. System Scope and Context[section-system-scope-and-context]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/03_system_scope_and_context.mmd]

# 4. Solution Strategy[section-solution-strategy]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/04_solution_strategy.mmd]

# 5. Building Block View [section-building-block-view]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/05_building_block_view.mmd]

# 6. Runtime View [section-runtime-view]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/06_runtime_view.mmd]

# 7. Deployment View [section-deployment-view]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/07_deployment_view.mmd]

# 8. Concepts [section-concepts]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/08_concepts.mmd]

# 9. Design Decisions [section-design-decisions]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/09_design_decisions.mmd]

# 10. Quality Scenarios [section-quality-scenarios]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/10_quality_scenarios.mmd]

# 11. Technical Risks [section-technical-risks]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/11_technical_risks.mmd]

# 12.  Glossary [section-glossary]#
<span style="font-size:smaller">[(Back to TOC)][TOC]</span>

<<[sections/12_glossary.mmd]

